# example netlify.toml
[build]
command = "npm run build"
functions = "functions"
publish = "dist"

[[redirects]]
from = '/api/*'
to = '/.netlify/functions/:splat'
status = 200

## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
[dev]
command = "npm run dev:nuxt"
